title_name = "Call of Duty: Modern Warfare 2"
title_id = "41560817" # AV-2071
hash = "A3FFB7C11B688FE5" # default_mp.xex
#media_id = "2C8C0267" # Disc (USA, Europe): http://redump.org/disc/11809

[[patch]]
    name = "Native 1280x720 resolution"
    desc = "Reduces flickering on upscaled resolutions x2 and x3"
    author = "mo"
    is_enabled = true

    # R_SetWndParms

    # wndParms->sceneWidth
    [[patch.be16]]
        address = 0x823C3E1E
        value = 0x0500       # 1024 -> 1280

    # wndParms->sceneHeight
    [[patch.be16]]
        address = 0x823C3E22
        value = 0x02d0       # 600 -> 720

    # wndParms->aaSamples
    [[patch.be16]]
        address = 0x823C3E36
        value = 0x0000       # 2 -> 0

[[patch]]
    name = "Increase memory allocation"
    desc = "Patches PMem_Init to allocate additional memory."
    author = "mo"
    is_enabled = true

    [[patch.be16]]
        address = 0x823129FA
        value = 0x1E00

    [[patch.be16]]
        address = 0x82312A1E
        value = 0x1E00
