"""Build t4_sp_index.json from a dump of stock World at War singleplayer scripts.

A dump can come from CoD Xe itself: set "dump_rawfile": true in _codxe/codxe.json, load a few
campaign and zombies levels, then point this script at game:\\_codxe\\dump. Scripts under
maps\\mp and clientscripts are skipped because multiplayer and CSC have different builtins.

A name counts as a builtin when stock scripts call it but no stock script defines it. Dev blocks
(/# ... #/) are stripped first, so dev-only builtins are not picked up.

Usage: python tools/gsc_check/build_index.py <dump_dir> [<dump_dir> ...]
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gsc_check import tokenize, LexError, SAFE_SCRIPTS, HERE  # noqa: E402


def script_key(root, full):
    rel = os.path.relpath(full, root).replace("/", "\\")
    return rel[:-4].lower() if rel.lower().endswith(".gsc") else rel.lower()


def scan(tokens):
    """Return (defs {name: param count}, called-as-function names, called-as-method names)."""
    defs, funcs, methods = {}, set(), set()
    depth = 0
    for i, t in enumerate(tokens):
        if t.kind == "eof":
            break
        if depth == 0 and t.kind == "ident" and tokens[i + 1].value == "(":
            j, params = i + 2, 0
            while tokens[j].value != ")" and tokens[j].kind != "eof":
                params += tokens[j].kind == "ident"
                j += 1
            if tokens[j + 1].value == "{":
                defs[t.value.lower()] = params
        if t.kind == "op" and t.value == "{":
            depth += 1
        elif t.kind == "op" and t.value == "}":
            depth -= 1
        elif depth > 0 and t.kind == "ident" and tokens[i + 1].value == "(":
            prev = tokens[i - 1]
            if prev.value == "::" or (prev.kind == "kw" and prev.value == "thread"):
                continue
            if prev.kind == "ident" or prev.value in ("]", ")"):
                methods.add(t.value.lower())
            else:
                funcs.add(t.value.lower())
    return defs, funcs, methods


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1

    scripts, all_defs = {}, set()
    func_files, method_files = {}, {}
    for root in sys.argv[1:]:
        for dirpath, _, names in os.walk(root):
            low = dirpath.replace("\\", "/").lower()
            if "/maps/mp" in low or "clientscripts" in low:
                continue
            for name in names:
                if not name.lower().endswith(".gsc"):
                    continue
                full = os.path.join(dirpath, name)
                with open(full, encoding="latin-1") as f:
                    try:
                        tokens = tokenize(f.read())
                    except LexError as e:
                        print("skipping %s: %s" % (full, e))
                        continue
                key = script_key(root, full)
                defs, funcs, methods = scan(tokens)
                scripts.setdefault(key, defs)
                all_defs.update(defs)
                for n in funcs:
                    func_files.setdefault(n, set()).add(key)
                for n in methods:
                    method_files.setdefault(n, set()).add(key)

    index = {
        "_comment": "Generated by build_index.py from stock World at War singleplayer scripts (dev blocks stripped). "
                    "functions/methods map builtin names to the number of stock scripts that call them; scripts holds "
                    "function signatures for the stock scripts every singleplayer level loads.",
        "functions": {n: len(f) for n, f in func_files.items() if n not in all_defs},
        "methods": {n: len(f) for n, f in method_files.items() if n not in all_defs},
        "scripts": {k: {"defs": scripts[k]} for k in (s.lower() for s in SAFE_SCRIPTS) if k in scripts},
    }
    out = os.path.join(HERE, "t4_sp_index.json")
    with open(out, "w") as f:
        json.dump(index, f, indent=1, sort_keys=True)
    print("wrote %s: %d scripts, %d builtin functions, %d builtin methods" % (
        out, len(scripts), len(index["functions"]), len(index["methods"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
